User.create(id: 1, name: "John Smith", email:"j@gmail.com", password_digest: "password")
User.create(id: 2, name: "Ted Smith", email:"c@gmail.com", password_digest: "password")
User.create(id: 3, name: "Bill Smith", email:"x@gmail.com", password_digest: "password")
User.create(id: 4, name: "Joe Smith", email:"w@gmail.com", password_digest: "password")
User.create(id: 5, name: "Ann Smith", email:"e@gmail.com", password_digest: "password")
User.create(id: 6, name: "Ted Smith", email:"f@gmail.com", password_digest: "password")
User.create(id: 7, name: "Phil Smith", email:"g@gmail.com", password_digest: "password")
User.create(id: 8, name: "Don Smith", email:"we@gmail.com", password_digest: "password")
User.create(id: 9, name: "Bobby Smith", email:"dee@gmail.com", password_digest: "password")
User.create(id: 10, name: "Heath Smith", email:"dce@gmail.com", password_digest: "password")
User.create(id: 11, name: "Jonas Smith", email:"qe@gmail.com", password_digest: "password")
User.create(id: 12, name: "Stan Smith", email:"b@gmail.com", password_digest: "password")
User.create(id: 13, name: "Alex Smith", email:"q@gmail.com", password_digest: "password")
User.create(id: 14, name: "Ted Smith", email:"b@gmail.com", password_digest: "password")
User.create(id: 15, name: "Nil Smith", email:"h@gmail.com", password_digest: "password")
User.create(id: 16, name: "Bobby Smith", email:"er@gmail.com", password_digest: "password")
User.create(id: 17, name: "Keith Smith", email:"op@gmail.com", password_digest: "password")
User.create(id: 18, name: "Nash Smith", email:"nonee@gmail.com", password_digest: "password")
User.create(id: 19, name: "DashSmith", email:"noqne@gmail.com", password_digest: "password")

Location.create(id: 1, city: "Queens", zip_location : "11377")
Location.create(id: 2, city: "Bronx", zip_location : "11377")
Location.create(id: 3, city: "Brooklyn", zip_location : "11377")
Location.create(id: 4, city: "Staten Island", zip_location : "11377")
Location.create(id: 5, city: "Manhattan", zip_location : "10001")


Post.create(id:1, name:"Hi everyone", user_id: 1, location_id: 1, content:"How are you all creeps doing?")
Post.create(id:2, name:"Hi Everyone", user_id: 2, location_id: 1, content:"How are you all creeps doing?")
Post.create(id:3, name:"Hi everyone", user_id: 3, location_id: 1, content:"How are you all creeps doing?")
Post.create(id:4, name:"Hi everyone", user_id: 4, location_id: 1, content:"How are you all creeps doing?")
Post.create(id:5, name:"Hi everyone", user_id: 5, location_id: 1, content:"How are you all creeps doing?")
Post.create(id:6, name:"Hi everyone", user_id: 6, location_id: 1, content:"How are you all creeps doing?")
Post.create(id:7, name:"Hi everyone", user_id: 7, location_id: 1, content:"How are you all creeps doing?")
Post.create(id:8, name:"Hi everyone", user_id: 8, location_id: 1, content:"How are you all creeps doing?")
Post.create(id:9, name:"Hi everyone", user_id: 9, location_id: 1, content:"How are you all creeps doing?")
Post.create(id:10, name:"Hi everyone", user_id: 10, location_id: 1, content:"How are you all creeps doing?")
Post.create(id:11, name:"Hi everyone", user_id: 11, location_id: 1, content:"How are you all creeps doing?")

Post.create(id:12, name:"Hi everyone", user_id: 1, location_id: 2, content:"How are you all creeps doing?")
Post.create(id:13, name:"Hi Everyone", user_id: 2, location_id: 2, content:"How are you all creeps doing?")
Post.create(id:14, name:"Hi everyone", user_id: 3, location_id: 2, content:"How are you all creeps doing?")
Post.create(id:15, name:"Hi everyone", user_id: 4, location_id: 2, content:"How are you all creeps doing?")
Post.create(id:16, name:"Hi everyone", user_id: 5, location_id: 2, content:"How are you all creeps doing?")
Post.create(id:17, name:"Hi everyone", user_id: 6, location_id: 2, content:"How are you all creeps doing?")
Post.create(id:18, name:"Hi everyone", user_id: 7, location_id: 2, content:"How are you all creeps doing?")
Post.create(id:19, name:"Hi everyone", user_id: 8, location_id: 2, content:"How are you all creeps doing?")
Post.create(id:20, name:"Hi everyone", user_id: 9, location_id: 2, content:"How are you all creeps doing?")
Post.create(id:21, name:"Hi everyone", user_id: 10, location_id: 2, content:"How are you all creeps doing?")
Post.create(id:22, name:"Hi everyone", user_id: 11, location_id: 2, content:"How are you all creeps doing?")

Post.create(id:23, name:"Hi everyone", user_id: 12, location_id: 3, content:"How are you all creeps doing?")
Post.create(id:24, name:"Hi Everyone", user_id: 13, location_id: 3, content:"How are you all creeps doing?")
Post.create(id:25, name:"Hi everyone", user_id: 14, location_id: 3, content:"How are you all creeps doing?")
Post.create(id:26, name:"Hi everyone", user_id: 15, location_id: 3, content:"How are you all creeps doing?")
Post.create(id:27, name:"Hi everyone", user_id: 16, location_id: 3, content:"How are you all creeps doing?")
Post.create(id:28, name:"Hi everyone", user_id: 17, location_id: 3, content:"How are you all creeps doing?")
Post.create(id:29, name:"Hi everyone", user_id: 18, location_id: 3, content:"How are you all creeps doing?")
Post.create(id:30, name:"Hi everyone", user_id: 19, location_id: 3, content:"How are you all creeps doing?")
Post.create(id:31, name:"Hi everyone", user_id: 20, location_id: 3, content:"How are you all creeps doing?")
Post.create(id:32, name:"Hi everyone", user_id: 10, location_id: 3, content:"How are you all creeps doing?")
Post.create(id:33, name:"Hi everyone", user_id: 11, location_id: 3, content:"How are you all creeps doing?")

Post.create(id:34, name:"Hi everyone", user_id: 12, location_id: 4, content:"How are you all creeps doing?")
Post.create(id:35, name:"Hi Everyone", user_id: 13, location_id: 4, content:"How are you all creeps doing?")
Post.create(id:36, name:"Hi everyone", user_id: 14, location_id: 4, content:"How are you all creeps doing?")
Post.create(id:37, name:"Hi everyone", user_id: 15, location_id: 4, content:"How are you all creeps doing?")
Post.create(id:38, name:"Hi everyone", user_id: 16, location_id: 4, content:"How are you all creeps doing?")
Post.create(id:39, name:"Hi everyone", user_id: 17, location_id: 4, content:"How are you all creeps doing?")
Post.create(id:40, name:"Hi everyone", user_id: 18, location_id: 4, content:"How are you all creeps doing?")
Post.create(id:41, name:"Hi everyone", user_id: 19, location_id: 4, content:"How are you all creeps doing?")
Post.create(id:42, name:"Hi everyone", user_id: 20, location_id: 4, content:"How are you all creeps doing?")
Post.create(id:43, name:"Hi everyone", user_id: 10, location_id: 4, content:"How are you all creeps doing?")
Post.create(id:44, name:"Hi everyone", user_id: 11, location_id: 4, content:"How are you all creeps doing?")

Post.create(id:45, name:"Hi everyone", user_id: 1, location_id: 5, content:"How are you all creeps doing?")
Post.create(id:46, name:"Hi Everyone", user_id: 2, location_id: 5, content:"How are you all creeps doing?")
Post.create(id:47, name:"Hi everyone", user_id: 3, location_id: 5, content:"How are you all creeps doing?")
Post.create(id:48, name:"Hi everyone", user_id: 4, location_id: 5, content:"How are you all creeps doing?")
Post.create(id:49, name:"Hi everyone", user_id: 5, location_id: 5, content:"How are you all creeps doing?")
Post.create(id:50, name:"Hi everyone", user_id: 6, location_id: 5, content:"How are you all creeps doing?")
Post.create(id:51, name:"Hi everyone", user_id: 7, location_id: 5, content:"How are you all creeps doing?")
Post.create(id:52, name:"Hi everyone", user_id: 8, location_id: 5, content:"How are you all creeps doing?")
Post.create(id:53, name:"Hi everyone", user_id: 9, location_id: 5, content:"How are you all creeps doing?")
Post.create(id:54, name:"Hi everyone", user_id: 10, location_id: 5, content:"How are you all creeps doing?")
Post.create(id:55, name:"Hi everyone", user_id: 11, location_id: 5, content:"How are you all creeps doing?")


# Comment.create(id: 1,post_id: 1,user_id: 1, content: "Cool story bro.")
# Comment.create(id: 2,post_id: 1,user_id: 2, content: "So cool.")
# Comment.create(id: 3,post_id: 1,user_id: 3, content: "Yeaaa sweet.")
# Comment.create(id: 4,post_id: 1,user_id: 4, content: "Wowza.")
# Comment.create(id: 5,post_id: 1,user_id: 5, content: "Noicee.")
#
# Comment.create(id: 1,post_id: 1,user_id: 1, content: "Cool story bro.")
# Comment.create(id: 2,post_id: 1,user_id: 2, content: "So cool.")
# Comment.create(id: 3,post_id: 1,user_id: 3, content: "Yeaaa sweet.")
# Comment.create(id: 4,post_id: 1,user_id: 4, content: "Wowza.")
# Comment.create(id: 5,post_id: 1,user_id: 5, content: "Noicee.")

for i in 1..55 do
  Comment.create(id: i,post_id: i,user_id: 1, content: "Cool story bro.")
end

for i in 1..55 do
  Comment.create(id: i + 55,post_id: i,user_id: 2, content: "So cool.")
end

for i in 1..55 do
  Comment.create(id: i + 110,post_id: i,user_id: 3, content: "Yeaaa sweet.")
end
